'use strict';

const DAY_OF_WEEK_FRIDAY = 5;
const DAY_OF_WEEK_SATURDAY = 6;
const DAY_OF_WEEK_SUNDAY = 0;
const NUM_WORK_DAYS = 5;
const WORK_HOUR_START = 9;
const WORK_HOUR_END = 17;
const WORK_HOURS_PER_DAY = 8;

module.exports = {
  DAY_OF_WEEK_FRIDAY,
  DAY_OF_WEEK_SATURDAY,
  DAY_OF_WEEK_SUNDAY,
  NUM_WORK_DAYS,
  WORK_HOUR_START,
  WORK_HOUR_END,
  WORK_HOURS_PER_DAY,
};
